### ISSUE TITLE
Support for shorthand hexadecimal colors like `#f60`

### ISSUE THREAD

**Issue by jgrancher** [nathsimpson/hex-alpha#11]
As the title says, it would be nice if this package supported shorthand hex values, so that you'd be able to do:

```javascript
hexAlpha("#f60", 0.1);
```

Let me know if you want any help with this!

**Comment by nathsimpson** [comment]
Great idea! I'll give it a go 👍

**Comment by nathsimpson** [comment]
Support for shorthand hexadecimal colors has been added in v1.1.0.
Thansks for the suggestion!
