### ISSUE TITLE
Bug when alpha 0

### ISSUE THREAD

**Issue by nejcm** [nathsimpson/hex-alpha#9]
https://github.com/nathsimpson/hex-alpha/blob/24163e48ce387b61ea79a9ceefebc7e436a8573d/index.js#L6

The if statement should be `if(alpha >= 0)` or `if(alpha !== undefined)` because if alpha is 0 it will be false and return the rgb value.

**Comment by nathsimpson** [comment]
Good spotting! I will make an update for this. Thank you

**Comment by nejcm** [comment]
Wanted to do a PR myself but was short on time when I reported the bug. Thanks!
